# Spring Cloud 配置
spring:
  application:
    name: yeff-springCloud-test
  main:
    allow-bean-definition-overriding: true
  cloud:
    # Nacos注册中心的配置
    nacos:
      discovery:
        # 对应本机的IP地址
        server-addr: 192.168.7.99:8848
        # 对应在Nacos中创建的命名空间
        namespace: 7c39c8b7-30ab-426c-ab7b-06ced9659e72
        group: yeff-springCloud-test
server:
  # Tomcat的端口号，也可以随机选择
  port: 8747
# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: com.yeff.springCloud
  protocol:
    name: dubbo
    port: 26756
  # Dubbo 服务注册中心的配置，对应 RegistryConfig 类
  registry:
    # 指定 Dubbo 服务注册中心的地址
    address: nacos://192.168.7.99:8848
  # Spring Cloud Alibaba Dubbo 的专属配置项，对应 DubboCloudProperties 类
  cloud:
    # 设置订阅的应用列表，多个用 （，）号分隔，默认为（ * ）表示订阅所有应用
    subscribed-services: "*"






